version: '3.8'

services:
  helloworldapp:
    image: anshudubey344/dotnet-pro:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

